export const SEED_USERS = [
  {
    id: 'u_sec',
    username: 'sec_admin',
    password_hash: 'pbkdf2_sec_2026',
    real_name: '赵安保 (安全保密员)',
    role: 'sec_admin',
    security_level: '机密',
    ca_sn: 'CA-SEC-998811',
    is_active: 1,
  },
  {
    id: 'u_sys',
    username: 'sys_admin',
    password_hash: 'pbkdf2_sys_2026',
    real_name: '钱运维 (系统管理员)',
    role: 'sys_admin',
    security_level: '机密',
    ca_sn: 'CA-SYS-998822',
    is_active: 1,
  },
  {
    id: 'u_aud',
    username: 'audit_admin',
    password_hash: 'pbkdf2_aud_2026',
    real_name: '孙审计 (安全审计员)',
    role: 'audit_admin',
    security_level: '机密',
    ca_sn: 'CA-AUD-998833',
    is_active: 1,
  },
  {
    id: 'u_arc',
    username: 'archivist',
    password_hash: 'pbkdf2_arc_2026',
    real_name: '李档案 (主责归档员)',
    role: 'archivist',
    security_level: '秘密',
    ca_sn: 'CA-ARC-998844',
    is_active: 1,
  },
  {
    id: 'u_usr',
    username: 'reader',
    password_hash: 'pbkdf2_usr_2026',
    real_name: '周查阅 (普通查阅员)',
    role: 'general_user',
    security_level: '内部',
    ca_sn: 'CA-USR-998855',
    is_active: 1,
  },
]

export const SEED_CONFIGS = [
  { key: 'SYSTEM_NAME', value: '陕飞工业数字档案管理协同系统 (信创涉密版)', description: '系统中文全称' },
  { key: 'BID_IDENTIFIER', value: '0730-2611010525/01', description: '标讯项目备案号' },
  { key: 'CLASSIFIED_PROTECTION_LEVEL', value: '三级等保/涉密分级保护 (机密级)', description: '分保等级要求' },
  { key: '18_MONTH_ZERO_DEFECT_GOAL', value: '540', description: '18个月零缺陷达标周期天数' },
]

export const SEED_NODES = [
  {
    node_id: 'XC-NODE-01',
    node_name: '陕飞档案主应用服务节点 A',
    cpu_arch: '鲲鹏 920 (64核)',
    os_name: '银河麒麟 Server V10',
    ip_address: '192.168.10.101',
    cpu_usage_pct: 28.4,
    memory_usage_pct: 45.2,
    storage_usage_pct: 38.1,
    consecutive_normal_days: 142,
    status: 'ONLINE',
    leak_index: 0.12,
    self_heal: 'IDLE',
  },
  {
    node_id: 'XC-NODE-02',
    node_name: '陕飞档案高可用备用节点 B',
    cpu_arch: '鲲鹏 920 (64核)',
    os_name: '银河麒麟 Server V10',
    ip_address: '192.168.10.102',
    cpu_usage_pct: 14.1,
    memory_usage_pct: 32.8,
    storage_usage_pct: 38.1,
    consecutive_normal_days: 142,
    status: 'ONLINE',
    leak_index: 0.08,
    self_heal: 'STANDBY',
  },
  {
    node_id: 'XC-NODE-03',
    node_name: '信创四性检测与OFD转码节点',
    cpu_arch: '飞腾 Tengyun S2500',
    os_name: '统信 UOS Server V20',
    ip_address: '192.168.10.103',
    cpu_usage_pct: 62.7,
    memory_usage_pct: 71.5,
    storage_usage_pct: 54.0,
    consecutive_normal_days: 142,
    status: 'ONLINE',
    leak_index: 0.31,
    self_heal: 'WATCH',
  },
  {
    node_id: 'XC-NODE-04',
    node_name: '涉密加密存储与不可篡改审计节点',
    cpu_arch: '海光 Hygon C86-3G',
    os_name: '银河麒麟 Server V10',
    ip_address: '192.168.10.104',
    cpu_usage_pct: 19.8,
    memory_usage_pct: 41.0,
    storage_usage_pct: 29.3,
    consecutive_normal_days: 142,
    status: 'ONLINE',
    leak_index: 0.05,
    self_heal: 'IDLE',
  },
]

export const SEED_ARCHIVES = [
  {
    id: 'arc_01',
    archive_code: 'SF-2026-YF-运9-001',
    title: '运-9系列机翼复合材料结构疲劳应力分析报告',
    category: '研发图纸',
    security_class: '机密',
    retention_period: '永久',
    file_size_bytes: 48291040,
    file_format: 'OFD',
    sha256_hash: 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855',
    four_check_status: 'PASSED',
    r2_object_key: 'archives/yf/y9_wing_stress_2026.ofd',
    archivist_id: 'u_arc',
    created_at: '2026-06-12 09:20:00',
  },
  {
    id: 'arc_02',
    archive_code: 'SF-2026-GY-陕飞-089',
    title: '某型特种机总装脉动生产线工艺流程卡',
    category: '工艺规程',
    security_class: '秘密',
    retention_period: '30年',
    file_size_bytes: 18451200,
    file_format: 'PDF/A',
    sha256_hash: 'f2ca1bb6c7e907d06dafe4687e579fce76b37e4e93b7605022da52e6ccc26fd2',
    four_check_status: 'PASSED',
    r2_object_key: 'archives/gy/assembly_proc_card.pdf',
    archivist_id: 'u_arc',
    created_at: '2026-07-03 14:11:00',
  },
  {
    id: 'arc_03',
    archive_code: 'SF-2026-ZL-试验-034',
    title: '数字化起落架液压作动器高低温环控测试原始记录',
    category: '质量试验',
    security_class: '内部',
    retention_period: '10年',
    file_size_bytes: 8392100,
    file_format: 'OFD',
    sha256_hash: '4b227777d4dd1fc61c6f884f48641d02b4d121d3fd328cb08b5531fcacdabf8a',
    four_check_status: 'PASSED',
    r2_object_key: 'archives/zl/landing_gear_env_test.ofd',
    archivist_id: 'u_arc',
    created_at: '2026-07-21 16:44:00',
  },
  {
    id: 'arc_04',
    archive_code: 'SF-2026-SB-数控-112',
    title: '五轴龙门加工中心年度计量校准与设备履历',
    category: '设备档案',
    security_class: '内部',
    retention_period: '30年',
    file_size_bytes: 12600320,
    file_format: 'PDF/A',
    sha256_hash: '6b86b273ff34fce19d6b804eff5a3f5747ada4eaa22f1d49c01e52ddb7875b4b',
    four_check_status: 'PENDING',
    r2_object_key: 'archives/sb/cnc_calib_2026.pdf',
    archivist_id: 'u_arc',
    created_at: '2026-08-08 10:02:00',
  },
  {
    id: 'arc_05',
    archive_code: 'SF-2026-ZH-综合-018',
    title: '汉中基地保密资格复查迎检材料汇编（脱敏演示）',
    category: '企业综合',
    security_class: '公开',
    retention_period: '10年',
    file_size_bytes: 4210880,
    file_format: 'OFD',
    sha256_hash: 'd4735e3a265e16eee03f59718b9b5d03019c07d8b6c51f90da3a666eec13ab35',
    four_check_status: 'PASSED',
    r2_object_key: 'archives/zh/security_review_pack.ofd',
    archivist_id: 'u_arc',
    created_at: '2026-05-19 11:30:00',
  },
  {
    id: 'arc_06',
    archive_code: 'SF-2026-YF-运9-044',
    title: '运-9货舱地板梁对接公差与工装定位数据集',
    category: '研发图纸',
    security_class: '秘密',
    retention_period: '永久',
    file_size_bytes: 90112000,
    file_format: 'DWG',
    sha256_hash: '4e07408562bedb8b60ce05c1decfe3ad16b72230967de01f640b7e4729b49fce',
    four_check_status: 'FAILED',
    r2_object_key: 'archives/yf/y9_floor_beam.dwg',
    archivist_id: 'u_arc',
    created_at: '2026-08-11 08:16:00',
  },
]

export const SEED_LOGS = [
  {
    id: 'aud_001',
    operator_id: 'u_sec',
    operator_role: 'sec_admin',
    client_ip: '192.168.1.15',
    action_type: 'SECURITY_CONFIG',
    resource_target: '密级访问控制策略表',
    security_classification: '机密',
    status: 'SUCCESS',
    details: '更新机密级文件调阅审批双人复核门槛',
    created_at: '2026-08-10 09:12:00',
  },
  {
    id: 'aud_002',
    operator_id: 'u_arc',
    operator_role: 'archivist',
    client_ip: '192.168.1.28',
    action_type: 'VIEW_ARCHIVE',
    resource_target: 'SF-2026-YF-运9-001',
    security_classification: '机密',
    status: 'SUCCESS',
    details: '电子档案密级水印动态载入并调阅',
    created_at: '2026-08-12 15:41:00',
  },
]

export const SEED_POLICIES = [
  { id: 'pol_mac', name: '强制访问控制 (MAC)', value: 'no-read-up', enabled: true, note: '主体密级不得低于客体密级' },
  { id: 'pol_dual', name: '机密级双人复核', value: 'dual-control', enabled: true, note: '机密调阅需安全保密员审批' },
  { id: 'pol_wm', name: '动态防伪水印', value: 'identity-timestamp-ip', enabled: true, note: '屏幕与导出均注入操作员身份' },
  { id: 'pol_three', name: '三员分立', value: 'enforced', enabled: true, note: '系统/安全/审计权限互斥' },
]

export const SEED_BORROWS = [
  {
    id: 'brw_001',
    archive_id: 'arc_03',
    archive_code: 'SF-2026-ZL-试验-034',
    title: '数字化起落架液压作动器高低温环控测试原始记录',
    security_class: '内部',
    requester_id: 'u_usr',
    requester_name: '周查阅 (普通查阅员)',
    purpose: '质量问题追溯复核',
    status: 'APPROVED',
    approver_id: 'u_sec',
    created_at: '2026-08-14 10:20:00',
  },
  {
    id: 'brw_002',
    archive_id: 'arc_02',
    archive_code: 'SF-2026-GY-陕飞-089',
    title: '某型特种机总装脉动生产线工艺流程卡',
    security_class: '秘密',
    requester_id: 'u_arc',
    requester_name: '李档案 (主责归档员)',
    purpose: '脉动线工艺改版对照',
    status: 'PENDING',
    approver_id: null,
    created_at: '2026-08-16 09:05:00',
  },
]

export const BID_NOTICE = {
  title: '数字档案管理系统招标公告',
  buyer: '陕西飞机工业有限责任公司',
  project_no: '0730-2611010525/01',
  publish_time: '2026/08/13 18:06:21',
  deadline: '2026-09-04 17:00:00',
  keywords: [
    '陕西飞机工业有限责任公司',
    '陕飞招标',
    '数字档案管理系统',
    '信创替代',
    '涉密信息系统集成',
    '0730-2611010525/01',
    '汉中招标',
    '航空工业',
  ],
  summary:
    '陕西飞机工业有限责任公司发布数字档案管理系统采购招标公告，需满足涉密分保与信创改造要求并含4台服务器，投标截止2026年9月4日。',
  technical_points: [
    {
      title: 'B/S 架构设计',
      body: '采用具备高可靠性、稳定性与易扩展性的 B/S 分布式架构。',
    },
    {
      title: '涉密分级保护合规',
      body: '全面遵循国家最新分保规范，落地密级标识、强制访问控制、“三员分立”管理、高强度身份鉴别与防篡改审计日志。',
    },
    {
      title: '软硬一体信创适配改造',
      body: '包含配套的 4 台信创专用服务器软硬件深度适配，支持纯国产环境平稳运行。',
    },
    {
      title: '18 个月超长无缺陷验证',
      body: '项目合同签订后需在 18 个月内无软件功能和逻辑问题发生方可最终通过验收。',
    },
  ],
  innovations: [
    {
      title: '全链路密级标签与零信任数据沙箱',
      body: '档案资产全生命周期附带多维密级安全元数据与动态人员水印防泄密。',
    },
    {
      title: '轻量化微服务/Serverless 高并发响应',
      body: '结合 Cloudflare 边缘计算与 D1/R2 体系，实现毫秒级档案元数据检索与大文件流式存储。',
    },
    {
      title: '信创服务器集群健康感知引擎',
      body: '实时监测 4 节点信创服务器计算资源与数据吞吐，提供长效稳定性预测保障。',
    },
  ],
  contacts: [
    { role: '招标人', name: '陕西飞机工业有限责任公司', place: '陕西省汉中市', phone: '0916-XXXX-6800' },
    { role: '项目联系人', name: '档案信息化办公室（演示脱敏）', place: '汉中基地', phone: '0916-XXXX-6812' },
  ],
  qualifications: [
    { id: 'q1', label: '独立法人资格及有效营业执照', required: true },
    { id: 'q2', label: '涉密信息系统集成或分保相关业绩', required: true },
    { id: 'q3', label: '信创服务器软硬件适配实施方案', required: true },
    { id: 'q4', label: '18 个月缺陷责任期承诺函', required: true },
    { id: 'q5', label: '三员分立与审计防篡改设计说明', required: true },
  ],
}

function clone(v) {
  return JSON.parse(JSON.stringify(v))
}

export function createMemoryState() {
  return {
    users: clone(SEED_USERS),
    configs: clone(SEED_CONFIGS),
    nodes: clone(SEED_NODES),
    archives: clone(SEED_ARCHIVES),
    logs: clone(SEED_LOGS),
    policies: clone(SEED_POLICIES),
    borrows: clone(SEED_BORROWS),
  }
}

export const memory = createMemoryState()
